
version: '3.7'

services:

  nginx:
    depends_on:
      - avatars
      - web
  web:
    depends_on:
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - differ
      - runner
      - saver
      - zipper
  zipper:
    depends_on:
      - saver
