
version: '3.7'

services:
# env-vars come from cyberdojo/versioner:latest

  nginx:
    image: ${CYBER_DOJO_NGINX_IMAGE}:${CYBER_DOJO_NGINX_TAG}

  # - - - - - - - - - - - - - - - - - - - - - - - -
  # start-points
  # see [cyber-dojo up --help] for details on how to override these
  custom-start-points:
    image: ${CYBER_DOJO_CUSTOM_START_POINTS}
  exercises-start-points:
    image: ${CYBER_DOJO_EXERCISES_START_POINTS}
  languages-start-points:
    image: ${CYBER_DOJO_LANGUAGES_START_POINTS}

  # - - - - - - - - - - - - - - - - - - - - - - - -
  # main services
  web:
    image: ${CYBER_DOJO_WEB_IMAGE}:${CYBER_DOJO_WEB_TAG}
  avatars:
    image: ${CYBER_DOJO_AVATARS_IMAGE}:${CYBER_DOJO_AVATARS_TAG}
  differ:
    image: ${CYBER_DOJO_DIFFER_IMAGE}:${CYBER_DOJO_DIFFER_TAG}
  ragger:
    image: ${CYBER_DOJO_RAGGER_IMAGE}:${CYBER_DOJO_RAGGER_TAG}
  runner:
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
  saver:
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
  zipper:
    image: ${CYBER_DOJO_ZIPPER_IMAGE}:${CYBER_DOJO_ZIPPER_TAG}
