
version: '3.7'

services:

  # - - - - - - - - - - - - - - - - - - - - - - -
  # multi-threaded front-end with http caching
  nginx:
    user: root
    init: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # main server (rails)
  web:
    user: nobody
    init: true
    environment:
      - CYBER_DOJO_SHA
      - CYBER_DOJO_RELEASE

  # - - - - - - - - - - - - - - - - - - - - - - -
  # start-points
  custom-start-points:
    user: nobody
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  exercises-start-points:
    user: nobody
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  languages-start-points:
    user: nobody
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # 64 animals
  avatars:
    user: nobody
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # runs cyber-dojo.sh in time-boxed container
  runner:
    user: root
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # converts runner's [stdout,stderr,status] to red/amber/green
  ragger:
    user: nobody
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # diffs all the files in two test events
  differ:
    user: nobody
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # stores groups/katas and code+tests for every test event
  saver:
    user: saver
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # provides tgz files of practice sessions
  zipper:
    user: nobody
    init: true
    environment: [ NO_PROMETHEUS ]
    read_only: true
