
version: '2.2'

volumes:
  # monitoring
  grafana_data: {}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

services:

  # - - - - - - - - - - - - - - - - - - - - - - -
  # multi-threaded front-end with http caching
  nginx:
    user: root
    init: true
    container_name: cyber-dojo-nginx
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure
    ports:
      - ${CYBER_DOJO_NGINX_PORT}:80

  # - - - - - - - - - - - - - - - - - - - - - - -
  # main server (rails)
  web:
    user: nobody
    init: true
    container_name: cyber-dojo-web
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure

  # - - - - - - - - - - - - - - - - - - - - - - -
  # start-points
  custom:
    user: nobody
    init: true
    container_name: cyber-dojo-custom
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure

  exercises:
    user: nobody
    init: true
    container_name: cyber-dojo-exercises
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure

  languages:
    user: nobody
    init: true
    container_name: cyber-dojo-languages
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure

  # - - - - - - - - - - - - - - - - - - - - - - -
  # runs cyber-dojo.sh in time-boxed container
  runner:
    user: root
    init: true
    container_name: cyber-dojo-runner
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - - - - - - - - -
  # convert runner's [stdout,stderr,status] to red/amber/green
  ragger:
    user: nobody
    init: true
    container_name: cyber-dojo-ragger
    read_only: true
    tmpfs: /tmp
    mem_limit: 32M
    memswap_limit: 32M
    restart: on-failure

  # - - - - - - - - - - - - - - - - - - - - - - -
  # stores groups/katas and code+tests for every test event
  saver:
    user: saver
    init: true
    container_name: cyber-dojo-saver
    read_only: true
    tmpfs: /tmp
    mem_limit: 256M
    memswap_limit: 256M
    restart: on-failure
    volumes:
      - /cyber-dojo:/cyber-dojo:rw

  # - - - - - - - - - - - - - - - - - - - - - - -
  # holds storer->saver id mappings created by porter
  mapper:
    user: nobody
    init: true
    container_name: cyber-dojo-mapper
    read_only: true
    tmpfs: /tmp
    mem_limit: 32M
    memswap_limit: 32M
    restart: on-failure
    volumes:
      - /porter:/porter:ro


  # - - - - - - - - - - - - - - - - - - - - - - -
  # diffs all the files in two test events
  differ:
    user: nobody
    init: true
    container_name: cyber-dojo-differ
    read_only: true
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: on-failure

  # - - - - - - - - - - - - - - - - - - - - - - -
  # provides tgz files of practice sessions
  zipper:
    user: nobody
    init: true
    container_name: cyber-dojo-zipper
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure

  # - - - - - - - - - - - - - - - - - - - - - - -
  # monitoring

  prometheus:
    init: true
    container_name: cyber-dojo-prometheus

  grafana:
    init: true
    container_name: cyber-dojo-grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - '3000:3000'
