
version: '2'

volumes:
  languages:
    external:
      name: ${CYBER_DOJO_START_POINT_LANGUAGES}
  exercises:
    external:
      name: ${CYBER_DOJO_START_POINT_EXERCISES}
  custom:
    external:
      name: ${CYBER_DOJO_START_POINT_CUSTOM}
  # monitoring
  grafana_data: {}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

services:

  # - - - - - - - - - - - - - - - - - - - - - - -
  # multi-threaded front-end with http caching

  nginx:
    user: root
    image: cyberdojo/nginx
    container_name: cyber-dojo-nginx
    cpu_shares: 1024
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure
    depends_on:
      - web
    env_file:
      - /app/nginx.env
    ports:
      - ${CYBER_DOJO_NGINX_PORT}:80

  # - - - - - - - - - - - - - - - - - - - - - - -
  # main server (rails)

  web:
    user: root
    image: cyberdojo/web
    container_name: cyber-dojo-web
    cpu_shares: 1024
    environment:
      - CYBER_DOJO_HOME
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    depends_on:
      - runner
      - runner_stateless
      - storer
      - differ
      - zipper
    env_file:
      - /app/web.env
    volumes:
      - languages:${CYBER_DOJO_HOME}/start_points/languages:ro
      - exercises:${CYBER_DOJO_HOME}/start_points/exercises:ro
      - custom:${CYBER_DOJO_HOME}/start_points/custom:ro

  # - - - - - - - - - - - - - - - - - - - - - - -
  # runs (statefully) code and tests written in browser

  runner:
    user: root
    image: cyberdojo/runner
    container_name: cyber-dojo-runner
    cpu_shares: 1024
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - - - - - - - - -
  # runs (statelessly) code and tests written in browser

  runner_stateless:
    user: root
    image: cyberdojo/runner_stateless
    container_name: cyber-dojo-runner-stateless
    cpu_shares:  1024
    read_only: true
    tmpfs: /tmp
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - - - - - - - - -
  # stores code+tests for every test event

  storer:
    user: cyber-dojo
    image: cyberdojo/storer
    container_name: cyber-dojo-storer
    cpu_shares: 1024
    read_only: true
    tmpfs: /tmp
    environment:
      - CYBER_DOJO_KATAS_ROOT
    volumes_from:
      - container:${CYBER_DOJO_KATAS_DATA_CONTAINER}:rw
    mem_limit: 2G
    memswap_limit: 2G
    restart: on-failure
    depends_on:
      - prometheus

  # - - - - - - - - - - - - - - - - - - - - - - -
  # diffs all the files in two test events

  differ:
    user: nobody
    image: cyberdojo/differ
    container_name: cyber-dojo-differ
    cpu_shares: 512
    read_only: true
    tmpfs: /tmp
    mem_limit: 1G
    memswap_limit: 1G
    restart: on-failure

  # - - - - - - - - - - - - - - - - - - - - - - -
  # garbage collects old volumes used by runner

  collector:
    user: root
    image: cyberdojo/collector
    container_name: cyber-dojo-collector
    cpu_shares: 256
    mem_limit: 1G
    memswap_limit: 1G
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # - - - - - - - - - - - - - - - - - - - - - - -
  # provides tgz files of kata sessions

  zipper:
    user: zipper
    image: cyberdojo/zipper
    container_name: cyber-dojo-zipper
    cpu_shares: 256
    read_only: true
    tmpfs: /tmp
    mem_limit: 50M
    memswap_limit: 50M
    restart: on-failure
    depends_on:
      - storer

  # - - - - - - - - - - - - - - - - - - - - - - -
  # monitoring

  prometheus:
    image: cyberdojo/prometheus
    container_name: cyber-dojo-prometheus
    cpu_shares: 128

  grafana:
    image: cyberdojo/grafana
    container_name: cyber-dojo-grafana
    cpu_shares: 128
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    env_file:
      - /app/grafana.env
    ports:
      - '3000:3000'
