
version: '2.2'

services:
  # overridable start-points. See .env file
  custom:
    image: ${CYBER_DOJO_CUSTOM}
  exercises:
    image: ${CYBER_DOJO_EXERCISES}
  languages:
    image: ${CYBER_DOJO_LANGUAGES}

  # main services
  differ:
    image: cyberdojo/differ:latest
  mapper:
    image: cyberdojo/mapper:latest
  nginx:
    image: cyberdojo/nginx:latest
  ragger:
    image: cyberdojo/ragger:latest
  runner:
    image: cyberdojo/runner:latest
  saver:
    image: cyberdojo/saver:latest
  web:
    image: cyberdojo/web:latest
  zipper:
    image: cyberdojo/zipper:latest

  # monitoring
  prometheus:
    image: cyberdojo/prometheus:latest
  grafana:
    image: cyberdojo/grafana:latest
