version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build image
          command: |
            set -ev
            ./sh/pipe_build_up_test.sh
      - run:
          name: publish image on dockerhub
          command: |
            set -ev
            readonly image=cyberdojo/commander
            docker tag  ${image}:latest ${image}:${CIRCLE_SHA1:0:7}
            docker tag  ${image}:latest ${image}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push ${image}:${CIRCLE_SHA1:0:7}
            docker push ${image}:beta

workflows:
  version: 2
  build:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
