version: 2
jobs:
  build-test-tag-publish:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build image, test it, tag it, publish it
          command: |
            set -e
            ./build_test_tag_publish.sh

workflows:
  version: 2
  build:
    jobs:
      - build-test-tag-publish:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
