version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build image
          command: |
            set -e
            sudo mkdir -p /cyber-dojo
            sudo chown 19663:65533 /cyber-dojo
            ./pipe_build_up_test.sh
      - run:
          name: publish image on dockerhub
          command: |
            set -e
            readonly PROJECT=${CIRCLE_PROJECT_REPONAME}
            readonly SHA_7=${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${PROJECT}:latest cyberdojo/${PROJECT}:${SHA_7}
            docker tag  cyberdojo/${PROJECT}:latest cyberdojo/${PROJECT}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/${PROJECT}:${SHA_7}
            docker push cyberdojo/${PROJECT}:beta
            docker push cyberdojo/${PROJECT}:latest

workflows:
  version: 2
  build:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
