version: 2
jobs:
  build-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build image
          command: |
            set -ev
            sudo mkdir -p /cyber-dojo
            sudo chown 19663:65533 /cyber-dojo
            ./pipe_build_up_test.sh
      - run:
          name: publish image on dockerhub
          command: |
            set -ev
            readonly project=${CIRCLE_PROJECT_REPONAME}
            docker run --rm -it cyberdojo/${project}:latest sh -c 'cat /etc/issue'
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/${project}:beta
            docker push cyberdojo/${project}:latest

workflows:
  version: 2
  build:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
