
version: '3.7'

services:

  nginx:
    container_name: cyber-dojo-nginx

  custom-start-points:
    container_name: cyber-dojo-custom-start-points
  exercises-start-points:
    container_name: cyber-dojo-exercises-start-points
  languages:
    container_name: cyber-dojo-languages

  avatars:
    container_name: cyber-dojo-avatars

  web:
    container_name: cyber-dojo-web

  runner:
    container_name: cyber-dojo-runner

  ragger:
    container_name: cyber-dojo-ragger

  differ:
    container_name: cyber-dojo-differ

  saver:
    container_name: cyber-dojo-saver

  zipper:
    container_name: cyber-dojo-zipper
