
version: '2.2'

services:
  differ:
    cpu_shares: 1024
  nginx:
    cpu_shares: 1024
  runner:
    cpu_shares: 1024
  saver:
    cpu_shares: 1024
  web:
    cpu_shares: 1024

  ragger:
    cpu_shares: 512

  mapper:
    cpu_shares: 128
  zipper:
    cpu_shares: 128

  custom:
    cpu_shares: 64
  exercises:
    cpu_shares: 64
  languages:
    cpu_shares: 64

  avatars:
    cpu_shares: 32

# cpu_shares
# https://docs.docker.com/engine/reference/run/#cpu-share-constraint
#
# The proportion will only apply when CPU-intensive processes
# are running.
#
# When tasks in one container are idle, other containers
# can use the left-over CPU time.
#
# On a multi-core system, the shares of CPU time are distributed
# over all CPU cores. Even if a container is limited to less than
# 100% of CPU time, it can use 100% of each individual CPU core.
