
version: '3.7'

services:

  nginx:
    depends_on:
      - avatars
      - web
  web:
    depends_on:
      - custom-start-points
      - differ
      - exercises
      - languages
      - ragger
      - runner
      - saver
      - zipper
  ragger:
    depends_on:
      - runner
  zipper:
    depends_on:
      - saver
