
version: '2.2'

services:

  nginx:
    depends_on:
      - web
  web:
    depends_on:
      - custom
      - differ
      - exercises
      - languages
      - mapper
      - ragger
      - runner
      - saver
      - versioner
      - zipper
  ragger:
    depends_on:
      - runner
  saver:
    depends_on:
      - mapper
  zipper:
    depends_on:
      - saver
  grafana:
    depends_on:
      - prometheus
