
version: '3.7'

services:

  # - - - - - - - - - - - - - - - - - - - - - - - -
  # start-points
  # see [cyber-dojo up --help] for details on how to override these
  custom:
    image: ${CYBER_DOJO_CUSTOM}
  exercises:
    image: ${CYBER_DOJO_EXERCISES}
  languages:
    image: ${CYBER_DOJO_LANGUAGES}

  # - - - - - - - - - - - - - - - - - - - - - - - -
  # main services
  # variables come from cyberdojo/versioner:latest
  web:
    image: ${CYBER_DOJO_WEB_IMAGE}:${CYBER_DOJO_WEB_TAG}
  avatars:
    image: cyberdojo/avatars:${CYBER_DOJO_AVATARS_TAG}
  differ:
    image: cyberdojo/differ:${CYBER_DOJO_DIFFER_TAG}
  mapper:
    image: cyberdojo/mapper:${CYBER_DOJO_MAPPER_TAG}
  nginx:
    image: cyberdojo/nginx:${CYBER_DOJO_NGINX_TAG}
  ragger:
    image: cyberdojo/ragger:${CYBER_DOJO_RAGGER_TAG}
  runner:
    image: cyberdojo/runner:${CYBER_DOJO_RUNNER_TAG}
  saver:
    image: cyberdojo/saver:${CYBER_DOJO_SAVER_TAG}
  zipper:
    image: cyberdojo/zipper:${CYBER_DOJO_ZIPPER_TAG}
