
version: '2.2'

services:
  # start-points (overridable)
  custom:
    image: ${CYBER_DOJO_CUSTOM}
  exercises:
    image: ${CYBER_DOJO_EXERCISES}
  languages:
    image: ${CYBER_DOJO_LANGUAGES}

  # main services
  differ:
    image: cyberdojo/differ:${CYBER_DOJO_DIFFER_TAG}
  mapper:
    image: cyberdojo/mapper:${CYBER_DOJO_MAPPER_TAG}
  nginx:
    image: cyberdojo/nginx:${CYBER_DOJO_NGINX_TAG}
  ragger:
    image: cyberdojo/ragger:${CYBER_DOJO_RAGGER_TAG}
  runner:
    image: cyberdojo/runner:${CYBER_DOJO_RUNNER_TAG}
  saver:
    image: cyberdojo/saver:${CYBER_DOJO_SAVER_TAG}
  web:
    image: cyberdojo/web:${CYBER_DOJO_WEB_TAG}
  zipper:
    image: cyberdojo/zipper:${CYBER_DOJO_ZIPPER_TAG}

  # monitoring
  grafana:
    image: cyberdojo/grafana:${CYBER_DOJO_GRAFANA_TAG}
  prometheus:
    image: cyberdojo/prometheus:${CYBER_DOJO_PROMETHEUS_TAG}
