
version: '2.2'

services:

  saver:
    mem_limit: 256M
    memswap_limit: 256M

  web:
    mem_limit: 128M
    memswap_limit: 128M

  nginx:
    mem_limit: 64M
    memswap_limit: 64M

  runner:
    mem_limit: 64M
    memswap_limit: 64M

  custom:
    mem_limit: 32M
    memswap_limit: 32M
  exercises:
    mem_limit: 32M
    memswap_limit: 32M
  languages:
    mem_limit: 32M
    memswap_limit: 32M
  avatars:
    mem_limit: 32M
    memswap_limit: 32M
  differ:
    mem_limit: 32M
    memswap_limit: 32M
  ragger:
    mem_limit: 32M
    memswap_limit: 32M
  mapper:
    mem_limit: 32M
    memswap_limit: 32M
  zipper:
    mem_limit: 32M
    memswap_limit: 32M
  versioner:
    mem_limit: 32M
    memswap_limit: 32M

# memory limits
# https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources
#
# mem_limit:
# Total memory limit not including swap.
# corresponds to [docker run --memory]
#
# memswap_limit:
# Total memory limit including swap.
# corresponds to [docker run --memory-swap]
