
version: '2.2'

services:
  runner:
    mem_limit: 4G
    memswap_limit: 4G

  differ:
    mem_limit: 1G
    memswap_limit: 1G
  web:
    mem_limit: 1G
    memswap_limit: 1G

  saver:
    mem_limit: 256M
    memswap_limit: 256M

  nginx:
    mem_limit: 128M
    memswap_limit: 128M

  custom:
    mem_limit: 32M
    memswap_limit: 32M
  exercises:
    mem_limit: 32M
    memswap_limit: 32M
  grafana:
    mem_limit: 32M
    memswap_limit: 32M
  languages:
    mem_limit: 32M
    memswap_limit: 32M
  ragger:
    mem_limit: 32M
    memswap_limit: 32M
  mapper:
    mem_limit: 32M
    memswap_limit: 32M
  prometheus:
    mem_limit: 32M
    memswap_limit: 32M
  zipper:
    mem_limit: 32M
    memswap_limit: 32M

# memory limits
# https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources
#
# mem_limit:
# Totoal memory limit not including swap.
# corresponds to [docker run --memory]
#
# memswap_limit:
# Total memory limit including swap.
# corresponds to [docker run --memory-swap]
