
version: '2.2'

services:
  runner:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  saver:
    volumes:
      - /cyber-dojo:/cyber-dojo:rw
  mapper:
    volumes:
      - /porter:/porter:ro
